### ISSUE TITLE
about prebaked Manhattan values

### ISSUE THREAD

**Issue by Leerw** [tpepin96/NYCDatasetProcessing#1]
Thank you for your code sharing,I want to know the csv longitude and latitude are only in the area of manhattan or in the whole nyc city? And the pprebaked manhattan values is only used for manhattan location? Also, how can I get the prebaked value of nyc whole city?

**Comment by lynnpepin** [comment]
Hi, sorry for this super late reply, I didn't see this when closed. It is just for Manhattan.

It's been awhile since I touched this, I forget how one would get these prebaked values for NYC. Manhattan was chosen since it is self-contained, high-traffic, and conveniently rectangle-shaped.
